# 测评使用，需放置在云主机 ～/
# 软件配置位于 config/config.toml

[problem.foobar]
docker_image = "c2rust_agent:latest"

# Where the codegen happens inside the container.
codegen_workdir = "/workspace"

# A non-shell command the checker will invoke for code generation.
# Replace with your actual end-to-end codegen entrypoint and args.
# For example, use your CLI to translate the test C project into a Cargo workspace under /workspace/out
codegen_command = "c2rust_agent --input /workspace/input_c_project --output /workspace/out"

# Log file for codegen stage.
codegen_logfile = "/workspace/run.log"

# The directory where the generated Rust Cargo project resides.
codegen_resultdir = "/workspace/out"

# Build the generated Cargo project. This is executed with cwd = codegen_resultdir.
build_command = "cargo build --release --locked"

# The path to the final executable. Point this to your compiled target if the evaluation expects a single exe.
# Adjust as needed for the specific project under test.
exe = "/workspace/out/target/release/translated_foobar"
