version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # HTTP API
      - "6334:6334"   # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage

  c2rust_agent:
    image: c2rust_agent:latest
    container_name: c2rust_agent
    # Build from local Dockerfile so the latest code is used; comment image above if you prefer local build only
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - qdrant
    working_dir: /opt/c2rust_agent
    # Mount the repo and persist DB; override config to point at qdrant service
    volumes:
      - ./config/docker.config.toml:/opt/c2rust_agent/config/config.toml:ro
      - sqlite_data:/opt/c2rust_agent/data
    ports:
      - "2222:22"     # SSH access to container
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    # Keep the container running by starting sshd in the foreground
    command: ["bash", "-lc", "mkdir -p /var/run/sshd && ssh-keygen -A && /usr/sbin/sshd -D"]
    # No entrypoint override; default CMD is bash from Dockerfile
    # Expose optional app-specific ports here if needed in the future

volumes:
  qdrant_storage:
  sqlite_data:
