# LLMConfig
# LLM Model config options
provider = "deepseek"
max_retry_attempts = 3
concurrent_limit = 5

[llm.ollama]
model = "deepseek-r1:7b"
base_url = "http://localhost:11434"
api_key = ""

[llm.openai]
model = "gpt-3.5-turbo"
api_key = "your_api_key_here"

[llm.xai]
model = "xai_model_name"
api_key = "your_api_key_here"

[llm.deepseek]
model = "deepseek-chat"
api_key = "sk-15a01570f9584076a2c4026e4bd1c8a0"

# DBConfig
# Database config options
[qdrant]
host = "localhost"
port = 6334
collection_name = "default"
vector_size = 1536

[sqlite]
path = "data.db"
