[package]
name = "relation_analy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
chrono = "0.4"

[dev-dependencies]
tempfile = { workspace = true }
